Update NFT-Marketplace-Part-1.md
LearnWeb3DAO/Celo-Track pull request #6
Opened 2022-08-03 11:31 UTC by yanukadeneth99

- Removed 'Equal to' in 2 places
- Changed the Chainlist link to open the Celo Alfajores Testnet straight
- Changed the purchase code to use the '_to.call' method and moved the delete to the end of the code. (Please check this, and let me know if that's incorrect).
- Fixed Indentation for Shipping it
- Fixed Emoji icons for Next Steps
- Added Discord Invite to showcase channel link

2022-08-03 15:14 UTC, haardikk21 requested changes

2022-08-03 15:49 UTC, yanukadeneth99 commented on NFT-Marketplace-Part-1.md
> +Drop your CeloScan link in the Discord [#showcase](https://discord.gg/HPunW7rAKb) channel and share your progress! See you in the next one 🌟
Yup.

2022-08-03 19:43 UTC, yanukadeneth99 commented on NFT-Marketplace-Part-1.md
> +    // Transfer ETH sent from buyer to seller
Sure, I'll look into that.

2022-08-03 19:44 UTC, yanukadeneth99 commented on NFT-Marketplace-Part-1.md
> +        delete listings[nftAddress][tokenId];
You might be right. If the `safeTransferFrom` or `call` fails, then the deletion is reverted right?

2022-08-04 09:04 UTC, yanukadeneth99 commented on NFT-Marketplace-Part-1.md
> +        delete listings[nftAddress][tokenId];
Changed this back.

2022-08-04 09:04 UTC, yanukadeneth99 commented
Changed the delete code location in : https://github.com/LearnWeb3DAO/Celo-Track/pull/6/commits/57d528d995bd72845381e391155a00f73abd30fd

2022-08-04 09:05 UTC, yanukadeneth99 commented on NFT-Marketplace-Part-1.md
> +    // Transfer ETH sent from buyer to seller
This is requested in PR : https://github.com/LearnWeb3DAO/Celo-Track/pull/7

2022-08-04 22:41 UTC, haardikk21 approved these changes

2022-08-04 22:41 UTC, merged